""" Module which contains lists with choices for forms """
class AllergyDataFormChoices:

    GENDER = [('Female', 'Female'),
              ('Male', 'Male'),
              ('Other', 'Other')]

    FAMILY_HISTORY = [(0, 'Select from below'),
                      ('No one', 'No one'),
                      ('Mother', 'Mother'),
                      ('Father', 'Father'),
                      ('Siblings', 'Siblings')]

    ALLERGIC_RHINITIS = [('Yes', 'Yes'), ('No', 'No')]

    ALLERGIC_ASTHMA = [('Yes', 'Yes'), ('No', 'No')]

    ALLERGIC_CONJUNCTIVITIS = [('Yes', 'Yes'), ('No', 'No')]

    ALLERGY_FREQUENCY = [('Extremely often', 'Extremely often'),
                         ('Often', 'Often'),
                         ('Sometimes', 'Sometimes'),
                         ('Rarely', 'Rarely')]

    ALLERGY_AFFECTION = [('It affects my sleep', 'It affects my sleep'),
                         ('It limits my everyday activities', 'It limits my everyday activities'),
                         ('It restricts my participation in school or work', 'It restricts my participation in school or work'),
                         ('It is very annoying', 'It is very annoying')]

    IMMUNOTHERAPY = [(0, 'Select from below'),
                     ('Sublingual (drops, tablets, nebulisation)', 'Sublingual (drops, tablets, nebulisation)'),
                     ('Injection', 'Injection'),
                     ('Other', 'Other'),
                     ('Not receiving immunotherapy', 'Not receiving immunotherapy')]

    MEDICINE_DAYS = [(0, 'Select from below'),
                     ('1', '1'),
                     ('2', '2'),
                     ('3', '3'),
                     ('4', '4'),
                     ('5', '5'),
                     ('6', '6'),
                     ('7', '7')]

    MEDICINE_WEEKS = [(0, 'Select from below'),
                      ('1', '1'),
                      ('2', '2'),
                      ('3', '3'),
                      ('4', '4'),
                      ('5 or more', '5 or more')]


class AllergySymptomsFormChoices:

    ALLERGY_SYMPTOMS_POLLEN_COM = [('Sneezing', 'Sneezing'),
                                   ('Wheezing', 'Wheezing'),
                                   ('Nasal Congestion', 'Nasal Congestion'),
                                   ('Coughing', 'Coughing'),
                                   ('Itchy, Watery Eyes', 'Itchy, Watery Eyes'),
                                   ('Runny Nose', 'Runny Nose'),
                                   ('Itchy throat', 'Itchy throat'),
                                   ('Stomach ache', 'Stomach ache'),
                                   ('Itchy skin', 'Itchy skin'),
                                   ('Hives', 'Hives'),
                                   ('Fatigue', 'Fatigue'),
                                   ('Irritability', 'Irritability')]


class AllergensFormChoices:

    ALLERGENS_SUBLIST_1 = [('Acacia', 'Acacia'),
                           ('Alder', 'Alder'),
                           ('Ash', 'Ash'),
                           ('Bald Cypress', 'Bald Cypress'),
                           ('Beech', 'Beech'),
                           ('Birch', 'Birch'),
                           ('Cattail', 'Cattail'),
                           ('Juniper', 'Juniper'),
                           ('Chenopods', 'Chenopods'),
                           ('Composites', 'Composites'),
                           ('Elm', 'Elm'),
                           ('Ephedra', 'Ephedra'),
                           ('Fir', 'Fir'),
                           ('Grasses', 'Grasses'),
                           ('Hackberry', 'Hackberry')]

    ALLERGENS_SUBLIST_2 = [('Hazelnut', 'Hazelnut'),
                           ('Hemp', 'Hemp'),
                           ('Hickory', 'Hickory'),
                           ('Goosefoot', 'Goosefoot'),
                           ('Linden', 'Linden'),
                           ('Locust', 'Locust'),
                           ('Maple', 'Maple'),
                           ('Mesquite', 'Mesquite'),
                           ('Mixed Trace', 'Mixed Trace'),
                           ('Mulberry', 'Mulberry'),
                           ('Bayberry', 'Bayberry'),
                           ('Nettle', 'Nettle'),
                           ('Oak', 'Oak'),
                           ('Olive', 'Olive'),
                           ('Osage Orange', 'Osage Orange')]

    ALLERGENS_SUBLIST_3 = [('Palm', 'Palm'),
                           ('Pellitory', 'Pellitory'),
                           ('Amaranth', 'Amaranth'),
                           ('Pine', 'Pine'),
                           ('Plantain', 'Plantain'),
                           ('Poplar', 'Poplar'),
                           ('Privet', 'Privet'),
                           ('Ragweed', 'Ragweed'),
                           ('Sagebrush', 'Sagebrush'),
                           ('Dock', 'Dock'),
                           ('SweetGum', 'SweetGum'),
                           ('Sycamore', 'Sycamore'),
                           ('Tree of Heaven', 'Tree of Heaven'),
                           ('Walnut', 'Walnut'),
                           ('Willow', 'Willow'),
                           ('Mold', 'Mold'),
                           ('Other', 'Other'),
                           ('I do not know', 'I do not know')]


class MedicinesFormChoices:

    ALLERGIC_RHINITIS_NOSE = [(0, 'Select from below'), 
                               ('Abelitan (Budesonide)', 'Abelitan (Budesonide)'),
                               ('Afluon (Azelastine)', 'Afluon (Azelastine)'),
                               ('Arsicort (Budesonide)', 'Arsicort (Budesonide)'),
                               ('Aurid (Budesonide)', 'Aurid (Budesonide)'),
                               ('Biosonide (Budesonide)', 'Biosonide (Budesonide)'),
                               ('Budekont (Budesonide)', 'Budekont (Budesonide)'),
                               ('Budemar (Budesonide)', 'Budemar (Budesonide)'),
                               ('Budenite (Budesonide)', 'Budenite (Budesonide)'),
                               ('Budeprol (Budesonide)', 'Budeprol (Budesonide)'),
                               ('Buderen (Budesonide)', 'Buderen (Budesonide)'),
                               ('Budesan (Budesonide)', 'Budesan (Budesonide)'),
                               ('Budesonal (Budesonide)', 'Budesonal (Budesonide)'),
                               ('Budesonide (Budesonide)', 'Budesonide (Budesonide)'),
                               ('Cromo-pos (Cromoglicic acid)', 'Cromo-pos (Cromoglicic acid)'),
                               ('Dexa rhinaspray (Dexamethasone / Tramazilone)', 'Dexa rhinaspray (Dexamethasone / Tramazilone)'),
                               ('Esonide (Budesonide)', 'Esonide (Budesonide)'),
                               ('Farlidone (Budesonide)', 'Farlidone (Budesonide)'),
                               ('Labetasol (Budesonide)', 'Labetasol (Budesonide)'),
                               ('Livostin (Levocabastine)', 'Livostin (Levocabastine)'),
                               ('Minalerg (Budesonide)', 'Minalerg (Budesonide)'),
                               ('Mometasone (Mometasone)', 'Mometasone (Mometasone)'),
                               ('Nasonex (Mometasone)', 'Nasonex (Mometasone)'),
                               ('Obecirol (Budesonide)', 'Obecirol (Budesonide)'),
                               ('Obuonid (Budesonide)', 'Obuonid (Budesonide)'),
                               ('Olfosonide (Budesonide)', 'Olfosonide (Budesonide)'),
                               ('Pulmicort nasal aq (Budesonide)', 'Pulmicort nasal aq (Budesonide)'),
                               ('Pulmovance (Budesonide)', 'Pulmovance (Budesonide)'),
                               ('Resata (Budesonide)', 'Resata (Budesonide)'),
                               ('Rhinobros (Budesonide)', 'Rhinobros (Budesonide)'),
                               ('Rhinoside (Budesonide)', 'Rhinoside (Budesonide)'),
                               ('Rinosol (Beclometasone)', 'Rinosol (Beclometasone)'),
                               ('Rinoster (Budesonide)', 'Rinoster (Budesonide)'),
                               ('Serbo (Budesonide)', 'Serbo (Budesonide)'),
                               ('Talgan (Budesonide)', 'Talgan (Budesonide)'),
                               ('Therasonid (Budesonide)', 'Therasonid (Budesonide)'),
                               ('Udesospray (Budesonide)', 'Udesospray (Budesonide)'),
                               ('Velorium (Budesonide)', 'Velorium (Budesonide)'),
                               ('Vericort (Budesonide)', 'Vericort (Budesonide)'),
                               ('Vinecort (Budesonide)', 'Vinecort (Budesonide)'),
                               ('Vividrin (Cromoglicic acid)', 'Vividrin (Cromoglicic acid)'),
                               ('Zefecort (Budesonide)', 'Zefecort (Budesonide)'),
                               ('Zyolaif (Budesonide)', 'Zyolaif (Budesonide)'),
                               ('Other (Budesonide)', 'Other (Budesonide)'),
                               ('None of the above', 'None of the above')]

    ALLERGIC_RHINITIS_MOUTH = [(0, 'Select from below'),
                               ('Adelcort (Prednisolone)', 'Adelcort (Prednisolone)'),
                               ('Betnesol (Betamethasone)', 'Betnesol (Betamethasone)'),
                               ('Bilagren (Bilastine)', 'Bilagren (Bilastine)'),
                               ('Bilaz (Bilastine)', 'Bilaz (Bilastine)'),
                               ('Biliranin (Loratadine)', 'Biliranin (Loratadine)'),
                               ('Bollinol (Loratadine)', 'Bollinol (Loratadine)'),
                               ('Celestone (Betamethasone)', 'Celestone (Betamethasone)'),
                               ('Cetirgen (Cetirizine)', 'Cetirgen (Cetirizine)'),
                               ('Clarityne (Loratadine)', 'Clarityne (Loratadine)'),
                               ('Contrahist (Levocetirizine)', 'Contrahist (Levocetirizine)'),
                               ('Cortineff (Fludrocortisone)', 'Cortineff (Fludrocortisone)'),
                               ('Decadron (Dexamethasone)', 'Decadron (Dexamethasone)'),
                               ('Deflan (Deflazacort)', 'Deflan (Deflazacort)'),
                               ('Dermizin (Cetirizine)', 'Dermizin (Cetirizine)'),
                               ('Dexamethasone (Dexamethasone)', 'Dexamethasone (Dexamethasone)'),
                               ('Dexaton (Dexamethasone)', 'Dexaton (Dexamethasone)'),
                               ('Fenistil (Dimetindene)', 'Fenistil (Dimetindene)'),
                               ('Flantadin (Deflazacort)', 'Flantadin (Deflazacort)'),
                               ('Florinef/BMS (Fludrocortisone)', 'Florinef/BMS (Fludrocortisone)'),
                               ('Gentiran (Cetirizine)', 'Gentiran (Cetirizine)'),
                               ('Habitek (Cetirizine)', 'Habitek (Cetirizine)'),
                               ('Hamiltosin (Cetirizine)', 'Hamiltosin (Cetirizine)'),
                               ('Histafren (Cetirizine)', 'Histafren (Cetirizine)'),
                               ('Hydrocortisone/???? (Hydrocortisone)', 'Hydrocortisone/???? (Hydrocortisone)'),
                               ('Istamex (Chlorphenamine)', 'Istamex (Chlorphenamine)'),
                               ('Kestine (Ebastine)', 'Kestine (Ebastine)'),
                               ('Latoren (Loratadine)', 'Latoren (Loratadine)'),
                               ('Levocet (Levocetirizine)', 'Levocet (Levocetirizine)'),
                               ('Levocetirizine/Actavis (Levocetirizine)', 'Levocetirizine/Actavis (Levocetirizine)'),
                               ('Levocetirizine/Teva (Levocetirizine)', 'Levocetirizine/Teva (Levocetirizine)'),
                               ('Lora (Loratadine)', 'Lora (Loratadine)'),
                               ('Medrol (Methylprednisolone)', 'Medrol (Methylprednisolone)'),
                               ('Oriens (Mizolastine)', 'Oriens (Mizolastine)'),
                               ('Phenergan (Promethazine)', 'Phenergan (Promethazine)'),
                               ('Predneau (Prednisolone)', 'Predneau (Prednisolone)'),
                               ('Prezolon (Prednisolone)', 'Prezolon (Prednisolone)'),
                               ('Ralinet (Loratadine)', 'Ralinet (Loratadine)'),
                               ('Rupafin (Rupatadine)', 'Rupafin (Rupatadine)'),
                               ('Sirodrol (Prednisolone)', 'Sirodrol (Prednisolone)'),
                               ('Soldesanil (Dexamethasone)', 'Soldesanil (Dexamethasone)'),
                               ('Suomi (Dexamethassone)', 'Suomi (Dexamethassone)'),
                               ('Telarix (Cetirizine)', 'Telarix (Cetirizine)'),
                               ('Utel (Loratadine)', 'Utel (Loratadine)'),
                               ('Xozal (Levocetirizine)', 'Xozal (Levocetirizine)'),
                               ('Zeda (Levocetirizine)', 'Zeda (Levocetirizine)'),
                               ('Zepholin (Cetirizine)', 'Zepholin (Cetirizine)'),
                               ('Zirtek (Cetirizine)', 'Zirtek (Cetirizine)'),
                               ('Znupril (Cetirizine)', 'Znupril (Cetirizine)'),
                               ('None of the above', 'None of the above')]

    ALLERGIC_RHINITIS_INJECTION = [(0, 'Select from below'), 
                                   ('Depo medrol (Methylprednisolone)', 'Depo medrol (Methylprednisolone)'),
                                   ('Dexamethasone/GAP (Dexamethasone)', 'Dexamethasone/GAP (Dexamethasone)'),  
                                   ('Dexaton (Dexamethasone)', 'Dexaton (Dexamethasone)'),
                                   ('Fenistil (Dimentidene)', 'Fenistil (Dimentidene)'),
                                   ('Kenacort (Triamcinolone acetonide)', 'Kenacort (Triamcinolone acetonide)'),  
                                   ('Lyo cortin (Hydrocortisone)', 'Lyo cortin (Hydrocortisone)'),  
                                   ('Lyo-drol (Methylprednisolone)', 'Lyo-drol (Methylprednisolone)'),  
                                   ('Prezolon (Prednisolone)', 'Prezolon (Prednisolone)'),
                                   ('Solu cortef (Hydrocortisone)', 'Solu cortef (Hydrocortisone)'),  
                                   ('Solu medrol (Methylprednisolone)', 'Solu medrol (Methylprednisolone)'),  
                                   ('Triamvirgi (Triamcinolone acetonide)', 'Triamvirgi (Triamcinolone acetonide)'),  
                                   ('Xolair (Omalizumab)', 'Xolair (Omalizumab)'),
                                   ('None of the above', 'None of the above')]

    ALLERGIC_ASTHMA_MOUTH = [(0, 'Select from below'), 
                             ('Aerolin (Salbutamol)', 'Aerolin (Salbutamol)'),
                             ('Aircast (Montelukast)', 'Aircast (Montelukast)'),
                             ('Alvesco (Ciclesonide)', 'Alvesco (Ciclesonide)'),
                             ('Andipulm (Formoterol)', 'Andipulm (Formoterol)'),
                             ('Apilone (Montelukast)', 'Apilone (Montelukast)'),
                             ('Ascolin (Montelukast)', 'Ascolin (Montelukast)'),
                             ('Asmaflex (Fluticasone)', 'Asmaflex (Fluticasone)'),
                             ('Asmanex (Mometasone)', 'Asmanex (Mometasone)'),
                             ('Asthmotrat (Salbutamol)', 'Asthmotrat (Salbutamol)'),
                             ('Atentus (Montelukast)', 'Atentus (Montelukast)'),
                             ('Atrovent (Ipratropium bromide)', 'Atrovent (Ipratropium bromide)'),
                             ('Becloneb (Beclometasone)', 'Becloneb (Beclometasone)'),
                             ('Beclospin (Beclometasone)', 'Beclospin (Beclometasone)'),
                             ('Biosonide (Budesonide)', 'Biosonide (Budesonide)'),
                             ('Bocacort (Fluticasone)', 'Bocacort (Fluticasone)'),
                             ('Brolyt (Montelukast)', 'Brolyt (Montelukast)'),
                             ('Broncoteril (Formoterol)', 'Broncoteril (Formoterol)'),
                             ('Broncovent (Ipratropium bromide)', 'Broncovent (Ipratropium bromide)'),
                             ('Budecol (Budesonide)', 'Budecol (Budesonide)'),
                             ('Budenofalk (Budesonide)', 'Budenofalk (Budesonide)'),
                             ('Choledyl (Choline theophyllinate)', 'Choledyl (Choline theophyllinate)'),
                             ('Ciplacombo (Fluticasone/Salmeterol)', 'Ciplacombo (Fluticasone/Salmeterol)'),
                             ('Daxas (Roflumilast)', 'Daxas (Roflumilast)'),
                             ('Demoren (Ipratropium bromide/Salbutamol)', 'Demoren (Ipratropium bromide/Salbutamol)'),
                             ('Edufil (Formoterol)', 'Edufil (Formoterol)'),
                             ('Flihaler (Fluticasone)', 'Flihaler (Fluticasone)'),
                             ('Flixotide (Fluticasone)', 'Flixotide (Fluticasone)'),
                             ('Flusalair (Fluticasone/Salmeterol)', 'Flusalair (Fluticasone/Salmeterol)'),
                             ('Fluticapen (Fluticasone)', 'Fluticapen (Fluticasone)'),
                             ('Foradil (Formoterol)', 'Foradil (Formoterol)'),
                             ('Forair (Formoterol)', 'Forair (Formoterol)'),
                             ('Forcap (Formoterol)', 'Forcap (Formoterol)'),
                             ('Formaxa (Formoterol)', 'Formaxa (Formoterol)'),
                             ('Formo-haler (Formoterol)', 'Formo-haler (Formoterol)'),
                             ('Formopen (Formoterol)', 'Formopen (Formoterol)'),
                             ('Formotil (Formoterol)', 'Formotil (Formoterol)'),
                             ('Foster (Beclometasone/Formoterol)', 'Foster (Beclometasone/Formoterol)'),
                             ('Hirobriz (Indacaterol)', 'Hirobriz (Indacaterol)'),
                             ('Imotec (Formoterol)', 'Imotec (Formoterol)'),
                             ('Ketotifen (Ketotifen)', 'Ketotifen (Ketotifen)'),
                             ('Miflonide (Budesonide)', 'Miflonide (Budesonide)'),
                             ('Miralust (Montelukast)', 'Miralust (Montelukast)'),
                             ('Modrian (Montelucast)', 'Modrian (Montelucast)'),
                             ('Modulair (Montelukast)', 'Modulair (Montelukast)'),
                             ('Mokast (Montelukast)', 'Mokast (Montelukast)'),
                             ('Molucar (Montelukast)', 'Molucar (Montelukast)'),
                             ('Moncas (Montelukast)', 'Moncas (Montelukast)'),
                             ('Montalis (Montelukast)', 'Montalis (Montelukast)'),
                             ('Montast (Montelukast)', 'Montast (Montelukast)'),
                             ('Montelair (Montelukast)', 'Montelair (Montelukast)'),
                             ('Montelukast/generics (Montelukast)', 'Montelukast/generics (Montelukast)'),
                             ('Montelukast/krka (Montelukast)', 'Montelukast/krka (Montelukast)'),
                             ('Montelukast/mylan (Montelukast)', 'Montelukast/mylan (Montelukast)'),
                             ('Montelukast/sandoz (Montelukast)', 'Montelukast/sandoz (Montelukast)'),
                             ('Montelukast/teva (Montelukast)', 'Montelukast/teva (Montelukast)'),
                             ('Nebulin (Budesonide)', 'Nebulin (Budesonide)'),
                             ('Olfo haler (Budesonide)', 'Olfo haler (Budesonide)'),
                             ('Onbrez breezhaler (Indacaterol)', 'Onbrez breezhaler (Indacaterol)'),
                             ('Oslif (Indacaterol)', 'Oslif (Indacaterol)'),
                             ('Oxez (Formoterol)', 'Oxez (Formoterol)'),
                             ('Pneumo-kast (Montelukast)', 'Pneumo-kast (Montelukast)'),
                             ('Pulmicort (Budesonide)', 'Pulmicort (Budesonide)'),
                             ('Pulmihal (Budesonide)', 'Pulmihal (Budesonide)'),
                             ('Pulmoton (Budesonide / Formoterol)', 'Pulmoton (Budesonide / Formoterol)'),
                             ('Qvar (Beclometasone)', 'Qvar (Beclometasone)'),
                             ('Relukas (Montelukast)', 'Relukas (Montelukast)'),
                             ('Resata (Budesonide)', 'Resata (Budesonide)'),
                             ('Rinosol (Beclometasone)', 'Rinosol (Beclometasone)'),
                             ('Rolenium (Fluticasone / Salmeterol)', 'Rolenium (Fluticasone / Salmeterol)'),
                             ('Salenga (Fluticasone)', 'Salenga (Fluticasone)'),
                             ('Salment (Salmeterol)', 'Salment (Salmeterol)'),
                             ('Seretide (Fluticasone / Salmeterol)', 'Seretide (Fluticasone / Salmeterol)'),
                             ('Serevent (Salmeterol)', 'Serevent (Salmeterol)'),
                             ('Signodem (Montelukast)', 'Signodem (Montelukast)'),
                             ('Singulair (Montelukast)', 'Singulair (Montelukast)'),
                             ('Singument (Montelukast)', 'Singument (Montelukast)'),
                             ('Spiriva (Tiotropium bromide)', 'Spiriva (Tiotropium bromide)'),
                             ('Spiropent (Clenbutarol)', 'Spiropent (Clenbutarol)'),
                             ('Symbicort (Budesonide / Formoterol)','Symbicort (Budesonide / Formoterol)'),
                             ('Talgan (Budesonide)', 'Talgan (Budesonide)'),
                             ('Theo-bros (Theophylline)', 'Theo-bros (Theophylline)'),
                             ('Theo-dur (Theophylline)', 'Theo-dur (Theophylline)'),
                             ('Thordel (Montelukast)', 'Thordel (Montelukast)'),
                             ('Tilade (Nedocromil)', 'Tilade (Nedocromil)'),
                             ('Uniphyllin (Theophylline)', 'Uniphyllin (Theophylline)'),
                             ('Velukast (Montelukast)', 'Velukast (Montelukast)'),
                             ('Vernoral (Budesonide)', 'Vernoral (Budesonide)'),
                             ('Yekast (Montelukast)', 'Yekast (Montelukast)'),
                             ('Zaditen (Ketotifen)', 'Zaditen (Ketotifen)'),
                             ('Zakomoxit (Montelukast)', 'Zakomoxit (Montelukast)'),
                             ('Zyrolen (Ipratropium bromide)', 'Zyrolen (Ipratropium bromide)'),
                             ('None of the above', 'None of the above')]

    ALLERGIC_CONJUNCTIVITIS_DROPS = [(0, 'Select from below'), 
                                    ('Allergotin (Cromoglicic acid)', 'Allergotin (Cromoglicic acid)'),
                                    ('Alopatan (Olopatadine)', 'Alopatan (Olopatadine)'),
                                    ('Cleroptic (Ketotifen)', 'Cleroptic (Ketotifen)'),
                                    ('Cromo-pos (Cromoglicic acid)', 'Cromo-pos (Cromoglicic acid)'),
                                    ('Cromodal (Cromoglicic acid)', 'Cromodal (Cromoglicic acid)'),
                                    ('Dovidin (Ketotifen)', 'Dovidin (Ketotifen)'),
                                    ('K-drops (Ketotifen)', 'K-drops (Ketotifen)'),
                                    ('Livostin (Levocabastine)', 'Livostin (Levocabastine)'),
                                    ('Meni-drops (Ketotifen)', 'Meni-drops (Ketotifen)'),
                                    ('Noxtor (Ketotifen)', 'Noxtor (Ketotifen)'),
                                    ('Opatanol (Olopatadine)', 'Opatanol (Olopatadine)'),
                                    ('Optallerg (Epinastine)', 'Optallerg (Epinastine)'),
                                    ('Relestat (Epinastine)', 'Relestat (Epinastine)'),
                                    ('Tilade (Nedocromil)', 'Tilade (Nedocromil)'),
                                    ('Urpem (Ketotifen)', 'Urpem (Ketotifen)'),
                                    ('Vividrin (Cromoglicic acid)', 'Vividrin (Cromoglicic acid)'),
                                    ('Zaditor (Ketotifen)', 'Zaditor (Ketotifen)'),
                                    ('Zethrinal (Ketotifen)', 'Zethrinal (Ketotifen)'),
                                    ('Zineli (Cromoglicic acid)', 'Zineli (Cromoglicic acid)'),
                                    ('None of the above', 'None of the above')]


class VasToolFormChoices:

    WORK_SCHOOL_TODAY = [('Yes', 'Yes'),
                         ('No', 'No')]
    
    ALLOW_ACCESS = [(0, 'Select from below'),
                    ('Yes', 'Yes'),
                    ('No', 'No')]
                    
                    # minutes, description
    TIME_INTERVAL = [(0, 'Select from below'),
                     (30, '30 minutes'),
                     (60, '1 Hour'),
                     (180, '3 Hours'),
                     (720, '12 Hours'),
                     (1440, '24 Hours'),
                     (4320, '3 Days'),
                     (10080, '1 Week'),
                     (43200, '1 Month'),
                     (129600, '3 Months'),
                     (259200, '6 Months'),
                     (518400, '1 Year')]


class HomeAllergensFormChoices:

    TIME_INTERVAL = [(0, 'Select from below'),
                     (30, '30 minutes'),
                     (60, '1 Hour'),
                     (180, '3 Hours'),
                     (720, '12 Hours'),
                     (1440, '24 Hours'),
                     (4320, '3 Days'),
                     (10080, '1 Week')]

    TIME_INTERVAL_TWITTER = [(0, 'Select from below (Default Today)'),
                             (30, '30 minutes'),
                             (60, '1 Hour'),
                             (180, '3 Hours'),
                             (720, '12 Hours'),
                             (1440, '24 Hours'),
                             (4320, '3 Days'),
                             (10080, '1 Week')]

    ALLERGENS_SUBLIST_1 = [('Acacia', 'Acacia'),
                           ('Alder', 'Alder'),
                           ('Ash', 'Ash'),
                           ('Bald Cypress', 'Bald Cypress'),
                           ('Beech', 'Beech'),
                           ('Birch', 'Birch'),
                           ('Cattail', 'Cattail'),
                           ('Juniper', 'Juniper'),
                           ('Chenopods', 'Chenopods'),
                           ('Composites', 'Composites'),
                           ('Elm', 'Elm'),
                           ('Ephedra', 'Ephedra'),
                           ('Fir', 'Fir'),
                           ('Grasses', 'Grasses'),
                           ('Hackberry', 'Hackberry')]

    ALLERGENS_SUBLIST_2 = [('Hazelnut', 'Hazelnut'),
                           ('Hemp', 'Hemp'),
                           ('Hickory', 'Hickory'),
                           ('Goosefoot', 'Goosefoot'),
                           ('Linden', 'Linden'),
                           ('Locust', 'Locust'),
                           ('Maple', 'Maple'),
                           ('Mesquite', 'Mesquite'),
                           ('Mixed Trace', 'Mixed Trace'),
                           ('Mulberry', 'Mulberry'),
                           ('Bayberry', 'Bayberry'),
                           ('Nettle', 'Nettle'),
                           ('Oak', 'Oak'),
                           ('Olive', 'Olive'),
                           ('Osage Orange', 'Osage Orange')]

    ALLERGENS_SUBLIST_3 = [('Palm', 'Palm'),
                           ('Pellitory', 'Pellitory'),
                           ('Amaranth', 'Amaranth'),
                           ('Pine', 'Pine'),
                           ('Plantain', 'Plantain'),
                           ('Poplar', 'Poplar'),
                           ('Privet', 'Privet'),
                           ('Ragweed', 'Ragweed'),
                           ('Sagebrush', 'Sagebrush'),
                           ('Dock', 'Dock'),
                           ('SweetGum', 'SweetGum'),
                           ('Sycamore', 'Sycamore'),
                           ('Tree of Heaven', 'Tree of Heaven'),
                           ('Walnut', 'Walnut'),
                           ('Willow', 'Willow'),
                           ('Mold', 'Mold')]